### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by pdalpra**
This is a major refactoring of teads-central tests, on two aspects:

### Keep only "blackbox" tests
Only exposed API is tested, which avoids testing some parts of the code twice (one time by testing the internals, one time by testing the exposed APIs).
This lead to some substantial simplification of tests and an overall cleanup of weird parts.

### Migrate to Ginkgo/Gomega
Ginkgo allows a better structuring of the tests, and as a bonus, has less external dependencies than Goconvey. We lose Goconvey's nice web UI, but no big deal :)

### CODE REVIEW

**Comment by pdalpra** [comment]
Additional benefit: when leaving the JUnit result files generation to Gingko, they are much more descriptive than what go-junit generates : https://jenkins.teads.net/job/tool-teads-central_pr/177/testReport/(root)/

**Comment by bjaglin** [comment]
This is a welcome, massive refactoring, so it's people from the CI/CD team who should review it IMHO (especially because it's the perfect occasion to spend a good amount of time catching up on the existing functionality here).

**Comment by pdalpra** [comment]
@gbougeard care to review ?

**Comment by gbougeard** [comment]
LGTM

**Pull request merged**
