### PR TITLE
Add release and download scripts

### PR DESCRIPTION
**Pull request by pdalpra**
This adds two scripts:

* `release.sh` performs a release of teads-central, ensuring that all tests passes in the process, and push the binaries to Github releases.
* `get.sh` downloads the latest version of teads-central, optionally filtering on a specific major version.

Tested on `michaelsauter/crane`:

```
$  MAJOR=0 ./get.sh
Getting crane v0.12.0...
$ ./crane version
v0.12.0
$ MAJOR=1 ./get.sh
Getting crane v1.5.1...
$ ./crane version
v1.5.1
$ ./get.sh
Getting crane v2.6.0...
$ ./crane version
v2.6.0
```

### CODE REVIEW

**Comment by pdalpra** [comment]
cc @ebuzzing/platform

**Comment by pdalpra** [comment]
ping

**Comment by gbougeard** [comment]
Shouldn't be on teads organization?

**Comment by TeaBough** [comment]
Maybe check that `GITHUB_TOKEN` is set.

**Comment by pdalpra** [comment]
Fixed !

**Comment by TeaBough** [comment]
LGTM

**Pull request merged**
