### PR TITLE
Migrate code to lib package

### PR DESCRIPTION
**Pull request by pdalpra**
This may seems unusual compared to existing Go code, but IMHO limiting the number of root folders makes it a bit easier to navigate the number, as you have:

* `cmd` for everything related to direct CLI interaction
* `lib` for the rest

This may be further refactored in the future if there is more 'utility code' such as `multierror` added to teads-central.

### CODE REVIEW

**Comment by pdalpra** [comment]
@PhilippeDupont @TeaBough any opinions on that ?

**Comment by bjaglin** [comment]
LGTM

**Comment by PhilippeDupont** [comment]
LGTM too

**Comment by TeaBough** [comment]
LGTM

**Pull request merged**
